package com.whtech.anuroopjodi.Object;

public class UserFullProfileObject {

    public String id;
    public String casteName;

/*    "id": "226",
            "package": "0",
            "birthTime": "0:0",
            "birthPlace": "333",
            "profileDescription": "I am currently pursuing PhD in biotechnology in pune and spend my free time watching sitcom, sketching or paintin. I  believe in balance in family and career and try to maintain it. I am looking for partner who is mature and understanding.",
            "loginId": "226",
            "ProfilePhoto": "profile-generic.jpg",
            "photoApproved": "0",
            "registrationNumber": null,
            "firstName": "bhagyashri",
            "emailId": "bhagyashri1292@gmail.com",
            "disability": "NO",
            "state": "15",
            "city": "333",
            "mobileNumber": "9537205274",
            "lastName": "joshi",
            "gender": "Female",
            "maritalStatus": "1",
            "gotra": "Kashyap",
            "birthDate": "1992-02-01",
            "religion": "0",
            "language": "6",
            "lifestyle": "Vegiterian",
            "height": "14",
            "weight": "65",
            "nakshatra": "Purvashada",
            "gan": "Manushya",
            "charan": "4",
            "blood": "O positive",
            "profileFor": "Self",
            "verified": "0",
            "status": "0",
            "featured": "0",
            "payment": "0",
            "entryDate": "2021-02-08 23:42:28",
            "subCast": "1",
            "income": "510000",
            "physique": "0",
            "occupation": "39",
            "education": "103,124",
            "company": "Agharkar Research Institute",
            "designation": "PhD student (CSIR-SRF)",
            "jobLocation": "Pune",
            "otherIncome": "00000",
            "complexion": "1",
            "manglik": "No",
            "nadi": "Madhya",
            "rashi": "Dhanur (Sagittarious)",
            "smoking": "NO",
            "hoteling": "",
            "primaryLanguage": "",
            "drinking": "",
            "fatherName": "Jayant Joshi",
            "motherName": "Shubhangi joshi",
            "brother": "0",
            "sister": "0",
            "father_occupation": "No more",
            "mother_occupation": "Home maker",
            "father_contact": "8141270804",
            "mother_contact": "8141270804",
            "sibling": "0",
            "married_sister": "0",
            "married_brother": "0",
            "uncle_name": "Suhas joshi",
            "uncle_occupation": "Retired",
            "m_uncle_name": "",
            "mama_occupation": "",
            "hobby": "Reading, writing articles, sketching, painting, listening music",
            "address": "Maninagar Ahmedabad",
            "lastSeen": "2021-02-09 00:24:57",
            "transactionId": null,
            "email_verified": "1",
            "mobile_verified": "1",
            "step1": "1",
            "step2": "1",
            "step3": "1",
            "step4": "1",
            "step5": "0",
            "payment_verification": "0",
            "state_name": "Gujarat",
            "city_name": "Ahmedabad",
            "marital_status": "Single",
            "language_name": "Marathi",
            "user_height": "5 ft 01  i",
            "occupation_name": "Student",
            "education_name": "MSC Biotechnology"*/
}
